stages:          # List of stages for jobs, and their order of execution
  - build
#  - deploy

variables:
  # DEPLOY_SSH_USER_AND_HOST: '$DEPLOY_SSH_USER@$DEPLOY_SSH_HOST'
  #DEV_SSH_USER_AND_HOST: '$DEV_DEPLOY_SSH_USER@$DEV_DEPLOY_SSH_HOST'
  #PROD_SSH_USER_AND_HOST: '$PROD_DEPLOY_SSH_USER@$PROD_DEPLOY_SSH_HOST'
  CI_REGISTRY: docker.fastoa.co
  IMAGE_TAG: $CI_REGISTRY/ch2/sscms:main
  #IMAGE_TAG: $CI_REGISTRY/ch2/gxskjj-api:$CI_COMMIT_REF_NAME


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - linux
  only:
    #- publish
    - local
  script:
    - npm install
    - npm run build-linux-x64  
    - docker build -t $IMAGE_TAG  .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
    - docker rmi $IMAGE_TAG