stages:          # List of stages for jobs, and their order of execution
  - build
#  - deploy

variables:
  # DEPLOY_SSH_USER_AND_HOST: '$DEPLOY_SSH_USER@$DEPLOY_SSH_HOST'
  #DEV_SSH_USER_AND_HOST: '$DEV_DEPLOY_SSH_USER@$DEV_DEPLOY_SSH_HOST'
  #PROD_SSH_USER_AND_HOST: '$PROD_DEPLOY_SSH_USER@$PROD_DEPLOY_SSH_HOST'
  CI_REGISTRY: docker.fastoa.co
  APP_VERSION: "7.3.1"
  #IMAGE_TAG: $CI_REGISTRY/ch2/gxskjj-api:$CI_COMMIT_REF_NAME


build-linux-64:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - linux
  only:
    #- publish
    - local
  variables:
    OS_VERSION: linux-x64  
    IMAGE_TAG: $CI_REGISTRY/ch2/sscms-$OS_VERSION:$APP_VERSION
  script:
    - docker build --no-cache --build-arg OS_VERSION=$OS_VERSION --build-arg APP_VERSION=$APP_VERSION -t $IMAGE_TAG  .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
    - docker rmi $IMAGE_TAG